# Generated by Django 5.1.15 on 2026-06-03 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_slug', models.SlugField(max_length=80, unique=True)),
                ('access_level', models.CharField(choices=[('OPEN_ACCESS', 'Accès libre'), ('METADATA_ONLY', 'Métadonnées seulement'), ('RESTRICTED_ACCESS', 'Accès restreint')], default='OPEN_ACCESS', max_length=30)),
                ('is_download_allowed', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archive_records', to='documents.documentversion')),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive_record', to='works.scientificwork')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
