# Generated by Django 5.1.15 on 2026-06-03 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0001_initial'),
        ('documents', '0001_initial'),
        ('institutions', '0001_initial'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schema_uri', models.CharField(blank=True, max_length=255)),
                ('schema_name', models.CharField(default='ScientificWorkArchiveCredential', max_length=120)),
                ('version', models.CharField(default='1.0', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CredentialSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_did', models.CharField(blank=True, max_length=255)),
                ('subject_type', models.CharField(choices=[('SCIENTIFIC_WORK', 'Travail scientifique'), ('AUTHOR', 'Auteur'), ('INSTITUTION', 'Institution')], default='SCIENTIFIC_WORK', max_length=30)),
                ('claims_json', models.JSONField(default=dict)),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_subjects', to='documents.documentversion')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_subjects', to='works.scientificwork')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecentralizedIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('did', models.CharField(max_length=255, unique=True)),
                ('method', models.CharField(default='web', max_length=40)),
                ('controller_type', models.CharField(choices=[('INSTITUTION', 'Institution'), ('USER', 'Utilisateur'), ('PLATFORM', 'Plateforme')], default='INSTITUTION', max_length=20)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dids', to='institutions.institution')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EidStackConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_url', models.URLField()),
                ('tenant_id', models.CharField(blank=True, max_length=120)),
                ('environment', models.CharField(choices=[('TEST', 'Test'), ('STAGING', 'Staging'), ('PRODUCTION', 'Production')], default='TEST', max_length=20)),
                ('api_credential_ref', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('connection_status', models.CharField(choices=[('CONNECTED', 'Connecté'), ('NOT_CONFIGURED', 'Non configuré'), ('AUTH_ERROR', 'Erreur authentification'), ('SERVICE_UNAVAILABLE', 'Service indisponible'), ('MISCONFIGURED', 'Mal configuré')], default='NOT_CONFIGURED', max_length=30)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eidstack_connection', to='institutions.institution')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerifiableCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_id', models.CharField(max_length=255, unique=True)),
                ('issuer_did', models.CharField(blank=True, max_length=255)),
                ('issuance_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('proof_format', models.CharField(choices=[('JWT_VC', 'JWT VC'), ('JSON_LD_VC', 'JSON-LD VC'), ('SD_JWT_VC', 'SD-JWT VC')], default='JWT_VC', max_length=20)),
                ('status', models.CharField(choices=[('ISSUED', 'Émis'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('REVOKED', 'Révoqué'), ('EXPIRED', 'Expiré')], default='ISSUED', max_length=20)),
                ('raw_credential_json', models.JSONField(default=dict)),
                ('is_mock', models.BooleanField(default=False)),
                ('schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='ssi.credentialschema')),
                ('subject', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential', to='ssi.credentialsubject')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CredentialStatusRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_list_url', models.URLField(blank=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=255)),
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_record', to='ssi.verifiablecredential')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proof_code', models.CharField(max_length=60, unique=True)),
                ('proof_type', models.CharField(choices=[('HASH_QR', 'Hash + QR'), ('VERIFIABLE_CREDENTIAL', 'Verifiable Credential')], default='VERIFIABLE_CREDENTIAL', max_length=30)),
                ('document_hash', models.CharField(max_length=64)),
                ('verification_url', models.URLField()),
                ('qr_code_url', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Révoquée'), ('EXPIRED', 'Expirée'), ('PENDING', 'En attente (SSI_PENDING)'), ('ERROR', 'Erreur')], default='ACTIVE', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('archive_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_proof', to='archive.archiverecord')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proofs', to='ssi.verifiablecredential')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(choices=[('VALID', 'Valide'), ('INVALID_HASH', 'Hash invalide'), ('NOT_FOUND', 'Introuvable'), ('REVOKED', 'Révoquée'), ('EXPIRED', 'Expirée'), ('TECHNICAL_ERROR', 'Erreur technique')], max_length=20)),
                ('source', models.CharField(choices=[('QR_CODE', 'QR code'), ('DIRECT_LINK', 'Lien direct'), ('MANUAL_INPUT', 'Saisie manuelle'), ('API', 'API')], default='QR_CODE', max_length=20)),
                ('client_ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64)),
                ('proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='ssi.verificationproof')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
