# Generated by Django 5.1.15 on 2026-06-03 16:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('works', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('ADMINISTRATIVE', 'Administrative'), ('SCIENTIFIC', 'Scientifique'), ('METADATA', 'Métadonnées'), ('PDF_FILE', 'Fichier PDF'), ('ABSTRACT', 'Résumé'), ('KEYWORDS', 'Mots-clés'), ('BIBLIOGRAPHY', 'Bibliographie'), ('VISIBILITY', 'Visibilité'), ('FINAL_VERSION', 'Version finale'), ('INSTITUTIONAL_COMPLIANCE', 'Conformité institutionnelle')], default='METADATA', max_length=30)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('NORMAL', 'Normale'), ('HIGH', 'Élevée'), ('BLOCKING', 'Bloquante')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('IN_PROGRESS', 'En traitement'), ('ANSWERED', 'Traitée'), ('VALIDATED', 'Validée'), ('REJECTED', 'Rejetée'), ('CANCELLED', 'Annulée')], default='OPEN', max_length=20)),
                ('related_page', models.PositiveIntegerField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='works.scientificwork')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_type', models.CharField(choices=[('AUTHORIZE_DEFENSE', 'Autoriser soutenance'), ('VALIDATE_AFTER_DEFENSE', 'Validé après soutenance'), ('REQUEST_CORRECTION', 'Demander correction'), ('ACCEPT_ARTICLE', 'Accepter article'), ('REJECT', 'Rejeter'), ('ARCHIVE', 'Archiver')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to=settings.AUTH_USER_MODEL)),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='documents.documentversion')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='works.scientificwork')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefenseSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_type', models.CharField(choices=[('MASTER_DEFENSE', 'Soutenance Master'), ('PHD_DEFENSE', 'Soutenance Doctorat')], max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('result', models.CharField(blank=True, choices=[('PASSED', 'Réussie'), ('PASSED_WITH_CORRECTIONS', 'Réussie avec corrections'), ('FAILED', 'Échouée'), ('POSTPONED', 'Reportée')], max_length=30, null=True)),
                ('jury_members', models.ManyToManyField(blank=True, related_name='jury_sessions', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_sessions', to='works.scientificwork')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValidationAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_type', models.CharField(choices=[('SUPERVISOR_REVIEW', 'Encadrement'), ('SCIENTIFIC_COMMITTEE', 'Comité scientifique'), ('PEER_REVIEW', 'Peer review'), ('ARCHIVE_CONTROL', 'Contrôle archive')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='works.scientificwork')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('recommendation', models.CharField(choices=[('ACCEPT', 'Accepter'), ('MINOR_CORRECTION', 'Correction mineure'), ('MAJOR_CORRECTION', 'Correction majeure'), ('REJECT', 'Rejeter')], max_length=20)),
                ('conformity_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='documents.documentversion')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='works.scientificwork')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='validation.validationassignment')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('event_type', models.CharField(choices=[('SUBMISSION', 'Soumission'), ('ASSIGNMENT', 'Affectation'), ('REVIEW', 'Avis'), ('CORRECTION', 'Correction'), ('DECISION', 'Décision'), ('ARCHIVE', 'Archivage'), ('CREDENTIAL_ISSUED', 'Preuve émise')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_events', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='works.scientificwork')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
