# Generated by Django 5.1.15 on 2026-06-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='attachment',
            field=models.FileField(blank=True, upload_to='reviews/'),
        ),
        migrations.AddField(
            model_name='review',
            name='internal_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='public_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='decision_type',
            field=models.CharField(choices=[('AUTHORIZE_DEFENSE', 'Autoriser soutenance'), ('RECORD_DEFENSE_PASSED', 'Soutenance réussie'), ('VALIDATE_AFTER_DEFENSE', 'Validé après soutenance'), ('REQUEST_CORRECTION', 'Demander correction'), ('REQUEST_MINOR_REVISION', 'Révision mineure'), ('REQUEST_MAJOR_REVISION', 'Révision majeure'), ('ACCEPT_ARTICLE', 'Accepter article'), ('PUBLISH_ARTICLE', 'Publier article'), ('ACCEPT_FINAL_DEPOSIT', 'Accepter dépôt final'), ('MARK_ARCHIVABLE', 'Rendre archivable'), ('REJECT', 'Rejeter'), ('ARCHIVE', 'Archiver')], max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='recommendation',
            field=models.CharField(choices=[('FAVORABLE', 'Favorable'), ('FAVORABLE_WITH_CORRECTIONS', 'Favorable avec corrections'), ('UNFAVORABLE', 'Défavorable'), ('REVISE', 'À réviser'), ('ACCEPT', 'Accepter'), ('MINOR_CORRECTION', 'Correction mineure'), ('MAJOR_CORRECTION', 'Correction majeure'), ('REJECT', 'Rejeter')], max_length=40),
        ),
        migrations.AlterField(
            model_name='validationassignment',
            name='assignment_type',
            field=models.CharField(choices=[('SUPERVISOR_REVIEW', 'Encadrement'), ('THESIS_DIRECTOR_REVIEW', 'Direction de thèse'), ('RAPPORTEUR_REVIEW', 'Rapporteur / expert'), ('SCIENTIFIC_COMMITTEE', 'Comité scientifique'), ('PEER_REVIEW', 'Peer review'), ('DEPARTMENT_DECISION', 'Décision département'), ('DOCTORAL_SCHOOL_REVIEW', 'École doctorale'), ('ARCHIVE_CONTROL', 'Contrôle archive')], max_length=30),
        ),
    ]
