# Generated by Django 5.1.15 on 2026-06-03 16:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('works', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=60)),
                ('model_name', models.CharField(max_length=120)),
                ('purpose', models.CharField(choices=[('METADATA_EXTRACTION', 'Extraction métadonnées'), ('SCIENTIFIC_SEARCH', 'Recherche scientifique'), ('SUMMARY', 'Résumé'), ('VALIDATION_ASSISTANCE', 'Aide à la validation')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIQueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('answer_status', models.CharField(choices=[('ANSWERED', 'Répondu'), ('NO_CONTEXT_FOUND', 'Aucun contexte'), ('FAILED', 'Échec'), ('FLAGGED', 'Signalé')], default='ANSWERED', max_length=20)),
                ('filters', models.JSONField(default=dict)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIAnswerCitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excerpt', models.TextField(blank=True)),
                ('score', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_citations', to='works.scientificwork')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='ai.aiquerylog')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetadataExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('extracted_title', models.CharField(blank=True, max_length=500)),
                ('extracted_abstract', models.TextField(blank=True)),
                ('extracted_keywords', models.JSONField(default=list)),
                ('suggested_domain', models.CharField(blank=True, max_length=255)),
                ('detected_language', models.CharField(blank=True, max_length=10)),
                ('confidence_score', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('raw_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('EXTRACTED', 'Extrait'), ('REVIEWED', 'Revu'), ('FAILED', 'Échec')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='documents.documentversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
