# Generated by Django 5.1.15 on 2026-06-03 16:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_role', models.CharField(blank=True, max_length=60)),
                ('action_type', models.CharField(choices=[('LOGIN', 'Connexion'), ('USER_CREATED', 'Utilisateur créé'), ('ROLE_CHANGED', 'Rôle modifié'), ('WORKFLOW_CHANGED', 'Workflow modifié'), ('PDF_UPLOADED', 'PDF déposé'), ('METADATA_UPDATED', 'Métadonnées modifiées'), ('REVIEW_ADDED', 'Avis ajouté'), ('CORRECTION_CREATED', 'Correction créée'), ('DECISION_RECORDED', 'Décision enregistrée'), ('DOCUMENT_ARCHIVED', 'Document archivé'), ('PROOF_ISSUED', 'Preuve émise'), ('PROOF_REVOKED', 'Preuve révoquée'), ('QR_VERIFIED', 'QR vérifié'), ('AI_SETTINGS_CHANGED', 'Paramètres IA modifiés'), ('SSI_SETTINGS_CHANGED', 'Paramètres SSI modifiés')], max_length=40)),
                ('module', models.CharField(blank=True, max_length=60)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('IMPORTANT', 'Important'), ('SENSITIVE', 'Sensible'), ('CRITICAL', 'Critique')], default='INFO', max_length=20)),
                ('object_status', models.CharField(blank=True, max_length=40)),
                ('comment', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='institutions.institution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
