# Generated by Django 5.1.15 on 2026-06-03 16:01

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(blank=True, max_length=60, unique=True)),
                ('type', models.CharField(choices=[('MEMOIRE', 'Mémoire'), ('THESE', 'Thèse'), ('ARTICLE', 'Article')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('abstract_text', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('FR', 'Français'), ('EN', 'Anglais'), ('OTHER', 'Autre')], default='FR', max_length=10)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('UNDER_REVIEW', 'En instruction'), ('CORRECTION_REQUESTED', 'Correction demandée'), ('RESUBMITTED', 'Re-soumis'), ('VALIDATED', 'Validé'), ('ARCHIVED', 'Archivé'), ('REJECTED', 'Rejeté')], default='DRAFT', max_length=30)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Privé'), ('INSTITUTION_ONLY', 'Institution'), ('PUBLIC', 'Public'), ('RESTRICTED', 'Restreint')], default='PRIVATE', max_length=20)),
                ('supervisor_name', models.CharField(blank=True, max_length=255)),
                ('scientific_domain', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_works', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='institutions.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='institutions.faculty')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='institutions.institution')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='institutions.academicprogram')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkContributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor_type', models.CharField(choices=[('AUTHOR', 'Auteur'), ('SUPERVISOR', 'Encadreur'), ('CO_SUPERVISOR', 'Co-encadreur'), ('REVIEWER', 'Reviewer'), ('RAPPORTEUR', 'Rapporteur'), ('JURY_MEMBER', 'Membre du jury')], default='AUTHOR', max_length=20)),
                ('display_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('orcid', models.CharField(blank=True, max_length=40)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='works.scientificwork')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
    ]
