# Generated by Django 5.1.15 on 2026-06-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_reference_code_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificwork',
            name='status',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('EN_INSTRUCTION', 'En instruction'), ('EN_PRE_INSTRUCTION', 'En pré-instruction'), ('EN_EXPERTISE', 'En expertise'), ('CORRECTION_DEMANDEE', 'Correction demandée'), ('RE_SOUMIS', 'Re-soumis'), ('AVIS_EN_ATTENTE', 'Avis en attente'), ('DECISION_REQUISE', 'Décision requise'), ('AUTORISE_SOUTENANCE', 'Autorisé soutenance'), ('SOUTENANCE_AUTORISEE', 'Soutenance autorisée'), ('SOUTENU', 'Soutenu'), ('CORRECTION_POST_SOUTENANCE', 'Correction post-soutenance'), ('VALIDE', 'Validé'), ('VALIDE_APRES_SOUTENANCE', 'Validé après soutenance'), ('DEPOT_FINAL_ACCEPTE', 'Dépôt final accepté'), ('SCREENING', 'Screening éditorial'), ('UNDER_REVIEW', 'Peer review'), ('REVISION_REQUESTED', 'Révision demandée'), ('RESUBMITTED', 'Article re-soumis'), ('ACCEPTED', 'Accepté'), ('PUBLISHED', 'Publié'), ('ARCHIVABLE', 'Archivable'), ('ARCHIVE', 'Archivé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=40),
        ),
    ]
