# Generated by Django 5.1.15 on 2026-06-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('DEPOSANT', 'Déposant'), ('SUPERVISOR', 'Encadreur'), ('THESIS_DIRECTOR', 'Directeur de thèse'), ('RAPPORTEUR', 'Rapporteur'), ('REVIEWER', 'Reviewer'), ('DEPARTMENT_HEAD', 'Chef de département'), ('SCIENTIFIC_COMMITTEE', 'Comité scientifique'), ('DOCTORAL_SCHOOL', 'École doctorale'), ('VALIDATOR', 'Validateur'), ('ARCHIVIST', 'Archiviste'), ('INSTITUTION_ADMIN', 'Administrateur institutionnel'), ('SUPER_ADMIN', 'Super administrateur'), ('TECHNICAL_ADMIN', 'Responsable SI / technique'), ('AUDIT_MANAGER', 'Responsable audit / qualité'), ('SCIENTIFIC_EDITOR', 'Éditeur scientifique'), ('PUBLIC', 'Public')], max_length=50, unique=True),
        ),
    ]
