# Generated by Django 5.1.15 on 2026-06-03 16:01

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('version_type', models.CharField(choices=[('INITIAL_SUBMISSION', 'Soumission initiale'), ('CORRECTED_VERSION', 'Version corrigée'), ('FINAL_ARCHIVE', 'Version finale archivée')], default='INITIAL_SUBMISSION', max_length=30)),
                ('file', models.FileField(upload_to=apps.documents.models.upload_to)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('sha256_hash', models.CharField(db_index=True, max_length=64)),
                ('change_note', models.TextField(blank=True)),
                ('is_final', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_versions', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='works.scientificwork')),
            ],
            options={
                'ordering': ['version_number'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_final', True)), fields=('work',), name='unique_final_version_per_work')],
            },
        ),
    ]
