# Generated by Django 5.1.15 on 2026-06-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('REPLACED', 'Remplacée'), ('UNDER_CORRECTION', 'En correction'), ('FINAL', 'Finale'), ('ARCHIVED', 'Archivée'), ('REJECTED', 'Rejetée')], default='ACTIVE', max_length=30),
        ),
    ]
