# Generated by Django 5.1.15 on 2026-06-03 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacetDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('source_field', models.CharField(max_length=120)),
                ('data_type', models.CharField(choices=[('TEXT', 'Texte'), ('NUMBER', 'Nombre'), ('DATE', 'Date'), ('ENUM', 'Énumération')], default='TEXT', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchIndexEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('normalized_title', models.CharField(max_length=500)),
                ('full_text_ref', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('INDEXED', 'Indexé'), ('FAILED', 'Échec')], default='PENDING', max_length=20)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('archive_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='index_entry', to='archive.archiverecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchFacetValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255)),
                ('normalized_value', models.CharField(max_length=255)),
                ('count_hint', models.PositiveIntegerField(blank=True, null=True)),
                ('facet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='search.facetdefinition')),
                ('index_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facet_values', to='search.searchindexentry')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
