export const endpoints = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    me: "/accounts/me",
  },
  works: {
    list: "/works",
    detail: (id: string) => `/works/${id}`,
    contributors: (id: string) => `/works/${id}/contributors`,
    documents: (id: string) => `/works/${id}/documents`,
    submit: (id: string) => `/works/${id}/submit`,
    history: (id: string) => `/works/${id}/history`,
    extractMetadata: (id: string) => `/works/${id}/extract-metadata`,
    metadataExtraction: (id: string) => `/works/${id}/metadata-extraction`,
    acceptMetadata: (id: string) => `/works/${id}/metadata/accept`,
    proof: (id: string) => `/works/${id}/proof`,
    similar: (id: string) => `/works/${id}/similar`,
    summary: (id: string) => `/works/${id}/summary`,
    assignments: (id: string) => `/works/${id}/assignments`,
    reviews: (id: string) => `/works/${id}/reviews`,
    corrections: (id: string) => `/works/${id}/corrections`,
    validateMetadata: (id: string) => `/works/${id}/metadata/validate`,
    decision: (id: string) => `/works/${id}/decision`,
    archive: (id: string) => `/works/${id}/archive`,
  },
  catalog: {
    list: "/catalog",
    search: "/catalog/search",
    facets: "/catalog/facets",
    detail: (slug: string) => `/catalog/${slug}`,
  },
  ai: {
    assistant: "/ai/assistant/query",
  },
  verify: (proofCode: string) => `/verify/${proofCode}`,
  institutions: "/institutions",
  faculties: "/faculties",
  departments: "/departments",
  programs: "/programs",
  validation: {
    inbox: "/validation/inbox",
  },
  admin: {
    dashboard: "/admin/dashboard",
    stats: "/admin/stats",
    audit: "/admin/audit",
    aiSettings: "/admin/ai-settings",
    searchSettings: "/admin/search-settings",
    documentTypes: "/admin/document-types",
    workflows: "/admin/workflows",
    workflowSteps: "/admin/workflow-steps",
    workflowTransitions: "/admin/workflow-transitions",
    ssiConnection: "/admin/ssi/connection",
    ssiTestConnection: "/admin/ssi/test-connection",
  },
  accounts: {
    users: "/accounts/users",
    roles: "/accounts/roles",
    permissions: "/accounts/permissions",
    userRoles: (id: string) => `/accounts/users/${id}/roles`,
  },
  ssi: {
    revoke: (id: string) => `/ssi/proofs/${id}/revoke`,
    reissue: (id: string) => `/ssi/proofs/${id}/reissue`,
  },
};
